### ISSUE TITLE
No IAM role error

### ISSUE THREAD

**Issue by Horizon-cmchugh** [sicarul/redshiftTools#5]
Hi there,

Recently discovered this package and am trying to get it to work. I installed as listed and am using a connection provided (that works with dbWriteTable from DBI) though RPostgreSQL. I'm getting the following error when attempting load a data frame of two columns and 100,000 rows (as a test case):

```
[1] "Getting number of slices from Redshift"
[1] "2 slices detected, will split into 8 files"
Error in get_ec2_role(verbose = verbose) : 
  No IAM role profile available in instance metadata
```
Note, previously I get an error saying that it needed a package called `aws.ec2metadata` installed, which does not seem to have been installed in the setup process. I installed it by doing `install.packages("aws.ec2metadata")`, which seemed to work, but I am still getting the above error.

Any ideas? Would love to use this package, seems fantastic.

**Comment by everron** [comment]
Hello , 

The issue here is due to an upgrade of aws.s3 package that matches aws.signature new credentials management (see https://github.com/cloudyr/aws.s3/commit/9627d8fe415ab9b293a02256a7e1e7645bd40052 )

One simple solution is to install aws.s3 3.3.0 directly from CRAN with `install.packages("aws.s3")`
and not from cloudyr repository. You can also remove aws.ec2metadata package

**Comment by sicarul** [comment]
Thanks @everron for the diagnosis and sorry for not seeing this, i'll change the instructions to use the CRAN package for now, i think it didn't exist when i created the package. I'll adapt the code to the accept the new changes too afterwards.

Thanks!
